27 | create UniversalModal
BUI-studies/yidlorama pull request #28
Opened 2024-06-10 18:30 UTC by NatashaLifer

Add component UniversalModal
https://github.com/BUI-studies/yidlorama/issues/27

2024-06-10 18:39 UTC, NatashaLifer commented on src/pages/Home.tsx
Nothing has changed in the file.

2024-06-20 16:32 UTC, BUI-studies requested changes
to complicated. start from scratch and write a simple modal window

2024-06-30 16:22 UTC, BUI-studies requested changes

2024-06-30 16:22 UTC, BUI-studies commented on src/components/UniversalModal/UniversalModal.tsx
> +const UniversalModal:FC<ModalProps> = (props) => {
```suggestion
const UniversalModal:FC<ModalProps> = ({ children, title, visible, setVisible  }) => {
```

2024-06-30 16:22 UTC, BUI-studies commented on src/components/UniversalModal/UniversalModal.tsx
> +    const { children, title, visible, setVisible  } = props
```suggestion

```

2024-06-30 16:22 UTC, BUI-studies commented on src/components/UniversalModal/UniversalModal.tsx
> +    const rootClasses = [classes.modal]
```suggestion
    const rootClasses = [classes.modal, visible ? rootClasses.push(classes.active) : '']
```

2024-06-30 16:22 UTC, BUI-studies commented on src/components/UniversalModal/UniversalModal.tsx
> +    visible ? rootClasses.push(classes.active) : null
```suggestion
```

2024-06-30 16:22 UTC, BUI-studies commented on src/pages/Home.tsx
revert back this file using git, so it doesn't appear in the PR.

2024-07-02 09:43 UTC, BUI-studies approved these changes

2024-07-07 16:03 UTC, yamnyk approved these changes

2024-07-07 16:03 UTC, merged